### ISSUE TITLE
require R version 4.0.5 for SSMSE?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#116]
Our tests were not passing for R 3.6.3 . I was going to check out locally, but ran into some issues with installing dependencies.

I'm wondering if you think it is worth troubleshooting this @nathanvaughan-NOAA  or if we should just update our minimum version of R ? The tests are working for 4.0.5, so we could use that as the minimum version, maybe?

@rwildermuth I'm also curious what version of R you are running? Would updating the minimum R version to 4.0.5 be a problem for you?

**Comment by k-doering-NOAA** [comment]
Also thanks @Bai-Li-NOAA  for allowing us to discover this by adding tests of older versions to https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/r-cmd-check.yml

**Comment by nathanvaughan-NOAA** [comment]
@k-doering-NOAA I'm happy with requiring 4.0.5 if that solves the issue. I would defer to @rwildermuth though for now so we don't break anything for them.

**Comment by rwildermuth** [comment]
I've been running things on 4.1+ lately, so that shouldn't affect us.

RW

**Comment by k-doering-NOAA** [comment]
Ok, I went ahead and required R 4.0.5. It is possible SSMSE works with older versions, but I think it isn't worth the time to sort out and rather to require updating.
