### ISSUE TITLE
Update to {roxygen2} to use _PACKAGE

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/SSMSE#128]
https://github.com/r4ss/r4ss/blob/03ea31db712125f7f9b8617935f1491ee171bddb/R/r4ss-package.R#L57

should be `"_PACKAGE"` as well as identifying the file as an internal file. See [guidance from the {roxygen2} vignette](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html#cb9-2). It is also recommended to name this file SSMSE-package.R instead of just SSMSE.R. It allows information to be ported from the DESCRIPTION to `?SSMSE` without having to retype it. See the [news feed for {roxygen2}](https://roxygen2.r-lib.org/articles/releases/roxygen2-6.0.0.html).
```
#' @keywords internal
"_PACKAGE"
```
https://github.com/nmfs-fish-tools/SSMSE/blob/4731fb09fd6408051f74d2bddf9c833275f3b6fe/R/SSMSE.R#L15

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA!

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA for fixing this in #191
