### ISSUE TITLE
modify dat_str list input

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#17]
The dat_str list input can be confusing, but we need some way to tell SSMSE what data it should be sampling in the future.  @nathanvaughan-NOAA and I developed some basic ideas on how to improve it. @iantaylor-NOAA, I know you mentioned the dat_str being confusing, so I would be happy to hear your feedback (either on these ideas, or on my first attempt toward implementing them), if you have time to give any. 

- [x] Rename dat_str to sample_struct to to make it more clear what the purpose is, to specify the sampling structure. (Or maybe there is another name that is even clearer?).
- [x]  make the naming more consistent. Currently, naming looks like: 
```
dat_str = list(
                   catch = data.frame(year = 101:106, seas = 1, fleet = 1),
                   CPUE = data.frame(year = c(102, 105), seas = 7, index = 2),
                   lencomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 1,
                                        Gender = 0, Part = 0),
                   agecomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 2,
                                        Gender = 0, Part = 0, Ageerr = 1,
                                        Lbin_lo = -1, Lbin_hi = -1)
```
This is based off of naming from r4ss::SS_readdat(). Make at least the names the user sees consistent so that it looks like:
```
dat_str = list(
                   catch = data.frame(Yr = 101:106, Seas = 1, FltSvy = 1),
                   CPUE = data.frame(Yr = c(102, 105), Seas = 7, FltSvy = 2),
                   lencomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 1,
                                        Sex = 0, Part = 0),
                   agecomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 2,
                                        Sex = 0, Part = 0, Ageerr = 1,
                                        Lbin_lo = -1, Lbin_hi = -1)
```
If it is easy to do so, also use the same col names for all of the dat_str components throughout SSMSE (this will only have issues if interfacing with r4ss).
- [x] Make SSMSE smarter so that the user doesn't need to specify all elements of the sampling scheme. For example, SSMSE can assume the Seas (season or month) when it is not specified based on the data already in the OM. Maybe SSMSE could report the assumptions back to the user.
- [x] Create a function to develop an initial version of dat_str from a data file and the number of years the MSE will run for.  For example, if CPUE is collected every 5 years in the OM, it will automatically specify a dat structure where CPUE continues to be collected every 5 years in the future projections. User can either pass this to run_SSMSE or modify it, if they want to specify a different sampling structure.

**Comment by iantaylor-NOAA** [comment]
Maybe we should make r4ss:SS_readdat (and maybe SS itself) more consistent in the column name conventions.

The proposed `sample_struct` seems more clear, but my initial confusion was around the difference between `dat_str` and `dat_str_list`. @k-doering-NOAA explained that "If you have multiple scenarios, there would be 2 lists specifying the data structure", but another way to deal with that would be to have `run_SSMSE` only work on a single scenario at a time (and perhaps add a wrapper function that could loop across scenarios and/or summarize across the results of separate calls to `run_MSE`).

I like the idea of filling in the seas, sex, partitions, ageerr, etc. automatically when there is a single value used through model (and warning when there isn't). Extrapolating CPUE frequency seems a bit more difficult as the timing of real data seems to often be inconsistent (unless its annually).

How are comp data sample sizes and index variability specified for those future years?

**Comment by k-doering-NOAA** [comment]
Thanks, @iantaylor-NOAA , I appreciate the feedback (esp. when I tagged you out of the blue)!
-  For now, I've made  a function to convert names from the consistent ones for user input to the r4ss ones. I'm not sure there is a good solution to making `r4ss::SS_readdat` more consistent, as I don't think there is a way to do it without breaking back compatibility. Happy to talk more about this, though, if you do want to go ahead with making r4ss or SS naming more consistent. 
- ok, @nathanvaughan-NOAA also thought `sample_struct` was more clear, as do I. 
- We already have the structure to run a single scenario in SSMSE, as there is a `run_SSMSE_scen` function (as well as one for `run_SSMSE_iter`, a single iteration of a scenario). Recently, I've been thinking it is simplest to route all users to the `run_SSMSE` wrapper (and maybe not even export `run_SSMSE_scen` and `run_SSMSE_iter` functions), but maybe it is not. I guess it would be easy to make this decision later, when more people have been able to try it out and decide which way they prefer. Thanks also for explaining your initial confusion, and I apologize for mis-remembering it!
- Thanks for the detail about CPUE. CPUE in the list refers to all the index of abundance data, in case that wasn't clear. I think in that case, the user would have to manually fill it in, unfortunately. 
- For comp data sample sizes and index variability, see #4 . Currently, SSMSE is just taking the most common value for the fleet and using it in the future. Obviously, this is not a very good option and is another avenue that I need to work on.  Maybe it does make sense for users to input their sample sizes/se's in the `dat_str` (to be renamed `sample_struct`?) if they want a custom option? If they wanted a different sample size input for the EM run from what was used to actually do the sampling, it seems that could be specified in `dat_str` as well.

Thank you for responding and helping me think this through- I really appreciate it!

**Comment by k-doering-NOAA** [comment]
Progress made on this issue. I will add some more tests for new functions created next week and also spend more time thinking about how users can input sample sizes, so leaving it open for now.

**Comment by k-doering-NOAA** [comment]
@nathanvaughan-NOAA and I briefly discussed sampling size input/se in future projections of the OM,  (#4 is also relevant), and decided that a good next step is adding an extra list component to `sample_struct` input so that users can put in their own custom values. 

This would look like:
```r
dat_str = list(
          catch = data.frame(Yr = 101:106, Seas = 1, FltSvy = 1, 
                           SE = 0.01), # standard error of 0.01 repeated for yrs 101 to 106
          CPUE = data.frame(Yr = c(102, 105), Seas = 7, FltSvy = 2, 
                          SE = c(0.01, 0.02)), # different standard error for each
          lencomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 1,
                               Nsamp = 100), # same input sample sizes for 102 and 105 obs.
          agecomp = data.frame(Yr = c(102, 105), Seas = 1, FltSvy = 2,
                               Nsamp = c(50, 105)) # different input sample sizes for each
)
```
Note that `SE` and `Nsamp` match with the labels in Stock Synthesis, so I plan to use these (unless there is a good reason to use different terms!)

In the future, we plan to add better default options in case the user does not want to specify (currently, the most common value from the historical period for each fleet will be used as the SE or Nsamp for every data observation). Perhaps some better options would be using an average or sampled from a distribution?

**Comment by k-doering-NOAA** [comment]
Left to do on this issue: 
- [ ] Add extra cols in `create_sample_struct` for age and length comps (like Lbin_lo and Lbin_hi; this would make their values more explicit to the user). 
- [ ] Use `create_sample_struct` in readme.md to illustrate use
- [ ] tests out `create_sample_struct` with more complex models (e.g., red grouper)
- [ ] run `devtools::document()`
- [ ] submit PR to merge in with master

**Comment by k-doering-NOAA** [comment]
When testing with more complex data files, it became apparent to me that most will result in some `NA` values being intentionally put in the `sample_struct` output generated by `create_sample_struct`. For example, if 1 year's observation is excluded for a index of abundance typically sampled annually (e.g., obs for 1995-2001, except missing for 1997), this will result in an `NA` for year for that fleet's sampling structure. As Ian pointed out, this is a common situation for indices of abundance. Maybe we could add options on to make the `create_sample_struct` function more useful for more complex sampling data, but I think it is still helpful as-is for now, as it least it allows the user to see an initial structure and be forced to decide how they want to sample into the future. I think we can revisit options in the future while thinking more about how users will interact with SSMSE.
