### ISSUE TITLE
Update starter file to calculate derived quantities in projection years

### ISSUE THREAD

**Issue by CassidyPeterson-NOAA** [nmfs-fish-tools/SSMSE#183]
Using the cod example, the starter file has a hard-wired maxyr_sdreport year = 101. This is copied to future model files, such that derived quantities are not calculated or reported in projection years. 

Consider adding a check to convert starter maxyr_sdreport = -2 to resolve this issue. 

This is a challenge when creating the new RatioMP for the FES MSE, which uses derived quantities in custom MP.

**Comment by k-doering-NOAA** [comment]
Good point! I think modifying the input files directly would fix this: https://github.com/nmfs-fish-tools/SSMSE/tree/main/inst/extdata/models/cod

However=, do you think we should change this to -2 for the user automatically in all model cases? If so, we can change this setting in the starter file when the user calls `run_SSMSE()`

**Comment by CassidyPeterson-NOAA** [comment]
Thanks, Kathryn! Yes, updating input file resolved the issue. I think it could be worth automating; I started to build some code but never got around to testing it.

**Comment by k-doering-NOAA** [comment]
Thanks, did @nathanvaughan-NOAA address this? Feel free to close if so!

**Comment by nathanvaughan-NOAA** [comment]
Yep these fixes are now included in main with PR#184. Skyler tested and they were working.
