### ISSUE TITLE
Nsamp for conditional age at length in sample_struct

### ISSUE THREAD

**Issue by mkapur-noaa** [nmfs-fish-tools/SSMSE#210]
After reading the description of [`sample_struct`](https://github.com/nmfs-fish-tools/SSMSE?tab=readme-ov-file#add-observation-error-through-sampling-from-om) and searching through the code, I'm not clear how specifying `Nsamp` for CAAL data gets treated in the data generation component.  Specifically, does the user need to specify a unique `Nsamp` value for each year-lengthbin combination in the future, and if so, what sort of additional sub setting is performed (a la [`ss3sim::sample_calcomp`](https://ss3sim.github.io/ss3sim/reference/sample_calcomp.html)) to produce the resultant simulated data?

**Comment by k-doering-NOAA** [comment]
@mkapur-noaa thanks for the question! SSMSE is just using the bootstrapping module of SS3 for sampling, so the sample sizes are as specified in the [ss3 user manual](https://nmfs-ost.github.io/ss3-doc/SS330_User_Manual_release.html#bootstrap-data-files):

> The sample size for conditional age-at-length data matches the inputs for each length bin. If stratified sampling is used, this may be appropriate, but if the ages represent a random subset of the selected population, this may result in less variability than if the associated length distribution were resampled.

I think it's correct that the user needs to provide a unique Nsamp for each year-lengthbin combination.

Let me know if that helps or if more clarification is still needed!

**Comment by k-doering-NOAA** [comment]
Thanks @mkapur-noaa! Thanks for reporting the issue with the helper function; I'll open a new issue to take a look at it.
