### ISSUE TITLE
Compare data generated to pass to EM to data of the historical period

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#25]
This would help us understand how "good" the data sets look when using the SS bootstrapping module. Start with the cod model OM, but could also look at other models. If appropriate, make this output generally accessible to users.

**Comment by k-doering-NOAA** [comment]
The 'plot_index_sampling' function in [results.R](https://github.com/nmfs-fish-tools/SSMSE/blob/main/R/results)  partially addresses this issue. also need a plot for composition data.

**Comment by k-doering-NOAA** [comment]
Here is the current
![plot_index_sampling image.](https://user-images.githubusercontent.com/48930335/103375130-32060980-4a8e-11eb-864b-1a0ecad73a50.png)

Note that the 2 indicates this is for fleet 2. If there were multiple fleets with data, a separate "facet" on the same plot would be created for each fleet.

@nathanvaughan-NOAA  do you have suggestions on how to improve this? Maybe it would be helpful to have fleet names instead of numbers as the labels, for example?

**Comment by nathanvaughan-NOAA** [comment]
I think going with the fleet names instead of numbers would be best as that
would also let the user modify these names as they like. Maybe we should
also add in a shaded polygon for the 95% CI of the expected values?

**Comment by k-doering-NOAA** [comment]
good point, both those changes make sense! I think the OM would have to be run with the hessian to get the 95% CI, which I'm not sure is done currently. Maybe we can just provide a warning if the hessian isn't available and let the user know what they could do to get one? (I think rerunning the OM model without estimation but with hessian should do the trick)

**Comment by nathanvaughan-NOAA** [comment]
I forgot we may not have run with the hessian. A warning if they haven't
run the hessian is good. We will have to double-check what happens with SS
for the hessian if you are not estimating values, I seem to remember having
some issues in the past but that would have been with 3.24

**Comment by k-doering-NOAA** [comment]
Working on the comps one also. I wonder if something like this r4ss plot would work?
![image of r4ss length comps plot with red lines added](https://user-images.githubusercontent.com/48930335/103377237-ad1dee80-4a93-11eb-8548-d142c8be3e41.png)

where the red lines I drew on would be the sampled data sets for each year, and would be included on each panel? (This is subplot 1 from the [SSplotcomps function](https://github.com/r4ss/r4ss/blob/development/R/SSplotComps.R#L125)) I think each panel in the plots represents the comps in a different year, and if there were multiple fleets with comps data, then there should be a different multipaneled plot for each fleet?

**Comment by k-doering-NOAA** [comment]
re hessians when not estimating, it is more likely the hessian won't invert if you are not in a good solution space, so that is certainly an issue folks could run into.

**Comment by nathanvaughan-NOAA** [comment]
That looks good for the comps unless we can come up with a more
succinct way than a million plots (but I haven't so far).

**Comment by k-doering-NOAA** [comment]
Adding some comments so I can return to this next week. The r4ss code needed to make this plot is in [subplot 1 of the SSPlotComps](https://github.com/r4ss/r4ss/blob/development/R/SSplotComps.R#L517). It uses the [make_multifig function](https://github.com/r4ss/r4ss/blob/development/R/make_multifig.R) . 

It may be possible to add onto the plot created if the pars of when the plot was created were passed back to SSMSE; Otherwise, the mapping will be difficult to do. The other option is to create a similar plot using ggplot. I am not sure which approach will pan out to be easier at this point, but will revisit the question next week.

**Comment by k-doering-NOAA** [comment]
Making progress on this, although it still needs some aesthetic tweaks and needs to be generalized for multiple fleets and 2 sex models.

![plot showing the expected OM values as a shaded area, with circle points for the OM historical data, and squares for the proportions from the generated data in squares](https://user-images.githubusercontent.com/48930335/103958279-75e9b600-5101-11eb-8e58-272c480e1399.png)

The plot above shows the expected OM values as a shaded area, with circle points for the OM historical data, and squares for the proportions from the generated data in squares.

Decided to use r4ss::SS_output to get the necessary numbers, but then create a plot with ggplot. I'm not sure why the proportions are nearly the same for all categories of values, it could just be that the when converting numbers of fish back to proportions they are very similar for this model.

**Comment by k-doering-NOAA** [comment]
Left to do is to get this working for 2 sex models and clean up issues with aesthetics.

**Comment by k-doering-NOAA** [comment]
I think this function has enough capabilities now. Plots are made by sex, fleet, season, and partition.

**Comment by rwildermuth** [comment]
> 
> 
> The current plot for index sampling with the cod model is below:
> ![plot_index_sampling image.](https://user-images.githubusercontent.com/48930335/103375130-32060980-4a8e-11eb-864b-1a0ecad73a50.png)
> 
> Note that the 2 indicates this is for fleet 2. If there were multiple fleets with data, a separate "facet" on the same plot would be created for each fleet.
> 
> @nathanvaughan-NOAA do you have suggestions on how to improve this? Maybe it would be helpful to have fleet names instead of numbers as the labels, for example?

I have a question about similar plots I'm trying to make for the Future Seas sardine MSE. I'm trying to pull and compare the OM "true" values, the samples from these OM values used as data in each iteration, and the EM estimated values for biomass and age/length composition. I'm able to compare the OM and EM values, but using r4ss::SS_readdat() to pull in the data file for the final year of each iteration, I see that the simulated data from OM values are the same across iterations, even in the projected period (2020-2024). Is this correct?

If I compare this to values in 'index_dat' resulting from SSMSE::plot_index_sampling(), there are different values among the iterations for "sampled_dataset", but they don't include the simulated samples for the projected period.

Please let me know if I'm looking in the correct directories/files to make these comparisons. My code is saved [here](https://github.com/futureseas/SardineMSE/blob/main/DocumentResults.Rmd).

Thanks! ~RW

**Comment by k-doering-NOAA** [comment]
Hi @rwildermuth , glad to hear you are making progress on the sardine MSE! Here are some responses.

> using r4ss::SS_readdat() to pull in the data file for the final year of each iteration, I see that the simulated data from OM values are the same across iterations, even in the projected period (2020-2024). Is this correct?

the OM "true" values will be identical for all iterations within a scenario, but can diverge in the projected period. Are the inputted catches from the projection period different among the iterations (this can be checked by openng up 2 OM datafiles and looking at the catches)? If not, identical catches could be the root cause of the OM true values looking the same in the projection period across iterations.

> If I compare this to values in 'index_dat' resulting from SSMSE::plot_index_sampling(), there are different values among the iterations for "sampled_dataset", but they don't include the simulated samples for the projected period.

Not including the simulated samples for the projection period in the plot_index_sampling may have been intentional - we developed this plot initially as a diagnostic to use while developing new ways to sample indices/comps (to make them a little more messy); unfortunately we only had time to create the diagnostic so far! I'm happy to modify this plot to include years in the projection period; at a glance, I couldn't find where in the code we may have been excluding simulated samples for the projection period, but I can dig into this more if it will be helpful for you.

**Comment by rwildermuth** [comment]
Thank you Kathryn, I've been able to track down the correct data and add them to our plots. I was able to confirm the catch and survey CPUE were different among the iterations in the OM and EM_year folders. 

No need to dig into the plot_index_sampling() function just yet, as I may modify and tweak this in my repository as I work on this project. Happy to share any modifications with you.

**Comment by k-doering-NOAA** [comment]
Excellent, feel free to reach out as things come up! I'll close this issue for now.
