### ISSUE TITLE
SSMSE's dependencies make install difficult

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#34]
First time install of SSMSE is taking a while due to package updates, and often the package update fails because it is previously being used by some other package also being updated. I think the best we can do is:
- [ ] eliminate any extra dependencies in SSMSE
- [x] consider whether some dependencies in r4ss can be eliminated
- [x] consider whether ss3sim has some dependencies that can be eliminated (although I think this was done already)

**Comment by kellijohnson-NOAA** [comment]
ss3sim did go through a bit of a elimination process, but I know more dependencies could be removed. I like `miniCRAN` for viewing the web of connections, e.g.,
```
install.packages("miniCRAN")
dg <- makeDepGraph("ss3sim",enhances = TRUE)
plot(dg)
```
![image](https://user-images.githubusercontent.com/4108564/91739214-73c98680-eb66-11ea-8e5d-c174b9bfcb83.png)

bbmle has limited function and could be removed and I need to finish removing the parallel capacity from ss3sim, which would also eliminate two packages and looks like two other packages that are dependencies of those.

**Comment by k-doering-NOAA** [comment]
Thanks for sharing this @kellijohnson-NOAA ! I didn't know about that graph function, it is pretty eye opening. Taking a look at r4ss dependencies to see if there are any that are barely being used (I know there were a few that @iantaylor-NOAA and I were able to move to "suggests" instead of "depends" earlier this year...)

**Comment by iantaylor-NOAA** [comment]
Thanks @kellijohnson-NOAA for the tip to use `miniCRAN`. 

I think it's worth noting that not all dependencies cause problems and the number of direct dependencies may be less of of an issue than a few dependencies which themselves have many dependencies.

Using the following commands with r4ss
```
dg <- miniCRAN::makeDepGraph("r4ss",enhances = TRUE)
igraph::tkplot(dg, vertex.color='white')
```
and then dragging things around to separate the 4 direct dependencies on the right from the suggests on the left provides the graph pasted below. This shows that `kableExtra` has lots of long chains of dependencies but the rest are pretty limited. Conversely `maps`, `truncnorm` and `pso` aren't dependent on anything so probably wouldn't be a big burden to move from `suggests` to `imports` in the future.

`kableExtra` is used by `r4ss::SS_makeHTMLdiagnostictable` which is a valuable addition but could theoretically be re-engineered to depend on a less powerful package instead, but the `kableExtra` recommendation here https://bookdown.org/yihui/rmarkdown-cookbook/kableextra.html suggests that it will be widely used and therefore more likely to get maintained well.
![image](https://user-images.githubusercontent.com/4992918/91780294-f6286980-ebab-11ea-89f1-14174b86f043.png)

**Comment by k-doering-NOAA** [comment]
thanks @kellijohnson-NOAA and @iantaylor-NOAA for creating these! I'm assuming I can't create one for SSMSE because it is not yet on CRAN, but I think most of its dependencies likely come from ss3sim and r4ss packages.

It looks like that most of the dependencies of kableExtra are due to rmarkdown and knitr, which I assume most people will have to download at some point anyway. I think the pkgs I've had issues with during install lately are things pretty far down the dependency chain, like  backports and glue. It seems to me that this is a wider R issue, where an installed package may require another package, so it is updated, but then R tries to update it again and is unsuccessful.

Maybe the best sol'n is to provide instructions on the readme for each of our pkgs in case people have problem with install, rather than try to eliminate dependencies. I think the advice would be to restart the R session, and use install.packages() to install the package that caused the issue; restart the R session, then try the `install_github()` command again. Or, perhaps someone has written some good troubleshooting R install issues somewhere that we could link to?

**Comment by kellijohnson-NOAA** [comment]
You can make install instructions that happen behind the scenes. I learned this from VAST. Or we could require these packages rather than only requiring dependencies of them. I find it annoying with ss3sim when I want to update and something is a dependency of both ss3sim and r4ss, so I get asked twice. I think the biggest problem for me happens when I try to install and I have already made calls to library() or I have other R windows that are open.

Does anyone know if the order of the dependencies in the DESCRIPTION file makes a difference? For instance, if you put the heavy hitter first and then all other packages then it would at least error out sooner rather than later. I get really annoyed when it has downloaded ten packages and then errors on one of the final ones.

Also, it seems to be problem for packages that require compilation more so than ones that don't because there will be a newer version available that requires compilation. Is there a way to specify that we don't want to compile any packages when installing SSMSE and instead we just want the old versions?

**Comment by k-doering-NOAA** [comment]
Wow, I had no idea you could have custom install instructions! [VAST install instructions](https://github.com/James-Thorson-NOAA/VAST#installation-instructions) has an option `INSTALL_opts` that can be used, is that what you are talking about Kelli? I also like that [known installation issues](https://github.com/James-Thorson-NOAA/VAST#known-installationusage-issues) are listed on the VAST readme.

I have no idea about order of dependencies, we would probably have to look at the code for `install_github` (or `install.packages`) to see. It would be great if we could order them a certain way.

And I support finding a way to select no compiling for SSMSE, if there is a way to do this. That question always confused me until very recently and I had no idea what the difference was between the options. I agree there is no reason to compile from source for the SSMSE dependencies.

I need to update R on one of my computers, so I will try to make note of the obstacles I encounter during install. I think they are all related to having r packages already loaded, @kellijohnson-NOAA , if I'm remembering correctly from the past.

**Comment by k-doering-NOAA** [comment]
Of course, the package install went smoothly this time. I think b/c I was using a fresh R library with no packages installed yet and so didn't need to update packages when running install_github. I did:
1. `install.packages("devtools")`  (probably should have tried remotes instead.)
2. restart session
3. `devtools::install_github("nmfs-fish-tools/SSMSE")` - I was asked 3x if I wanted to updated installed package (for ss3sim, r4ss, and SSMSE; I'm assuming if I used CRAN versions of ss3sim and r4ss this wouldn't happen?) I clicked "no" each time.

maybe for now, I will just start by adding a small "install troubleshooting" section to the SSMSE readme. I don't think the install will be surprising for users that regularly install packages from github (although it can be annoying), but might be confusing for folks who are less frequent R users. If install seems to be a major sticking point, then I think going the formal route of specialized install instructions makes sense.

**Comment by kellijohnson-NOAA** [comment]
The [staged install](https://developer.r-project.org/Blog/public/2019/02/14/staged-install/) thing has to do with this packages being partially installed when trying to download. Which is a different R-wide issue. I was referring to VAST's [`.onAttach`](https://github.com/James-Thorson-NOAA/VAST/blob/master/R/zzz.R) instructions.

**Comment by k-doering-NOAA** [comment]
Ah, I see, thanks for linking the .onAttach instructions! I have seen other packages do this, but didn't know how it is done.

I think for now this section might help users: https://github.com/nmfs-fish-tools/SSMSE#troubleshooting-installation ; but if it turns out there are deeper problems, I will revisit this issues and the solutions proposed.

Thanks @kellijohnson-NOAA  and @iantaylor-NOAA  for discussion on this topic!
